
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=controlvehicular

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=controlvehicular
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: